import pandas as pd
import sqlite3
import wx
import wx.grid

#pass parameters
class Signal(object):
    def __init__(self,name): # real signature unknown
        self.name=name

    def connect(self,fun):
        self.emit=fun

# columns heading
columns = ['id','listing_url','scrape_id','last_scraped','name','summary','space',
           'description','experiences_offered','neighborhood_overview','notes',
           'transit','access','interaction','house_rules','thumbnail_url',
           'medium_url','picture_url','xl_picture_url','host_id','host_url',
           'host_name','host_since','host_location','host_response_time',
           'host_response_rate','host_acceptance_rate','host_is_superhost','host_thumbnail_url',
           'host_picture_url','host_neighbourhood','host_listings_count','host_total_listings_count',
           'host_verifications','host_has_profile_pic','host_identity_verified','street',
           'neighbourhood','neighbourhood_cleansed','neighbourhood_group_cleansed','city',
           'state','zipcode','market','smart_location','country_code','country','latitude',
           'longitude','is_location_exact','property_type','room_type','accommodates','bathrooms',
           'bedrooms','beds','bed_type','amenities','square_feet','price','weekly_price',
           'monthly_price','security_deposit','cleaning_fee','guests_included','extra_people',
           'minimum_nights','maximum_nights','calendar_updated','has_availability','availability_30',
           'availability_60','availability_90','availability_365','calendar_last_scraped',
           'number_of_reviews','first_review','last_review','review_scores_rating','review_scores_accuracy',
           'review_scores_cleanliness','review_scores_checkin','review_scores_communication',
           'review_scores_location','review_scores_value','requires_license','license','jurisdiction_names',
           'instant_bookable','is_business_travel_ready','cancellation_policy','require_guest_profile_picture',
           'require_guest_phone_verification','calculated_host_listings_count','reviews_per_month']

# inheritied frame
class MyGridTable(wx.grid.GridTableBase):
    def __init__(self, data, rows):
        super().__init__()
        self.data = data
        self.colLabels = columns
        self.rowLabels = rows
    def GetNumberRows(self):
        return len(self.data)
    def GetNumberCols(self):
        return len(self.colLabels)
    def GetValue(self, row, col):
        return self.data[row][col]
    def GetColLabelValue(self, col):
        return self.colLabels[col]
    def GetRowLabelValue(self, row):
        return self.rowLabels[row]

class MyGridTable5(wx.grid.GridTableBase):
    def __init__(self, data, rows):
        super().__init__()
        self.data = data
        self.num_rows = len(data)
        self.num_cols = 5  # Set the number of columns to 4
        self.colLabels = ["id", "name", "review_scores_rating", "review_scores_cleanliness", "number_of_reviews"]
        self.rowLabels = rows

    def GetNumberRows(self):
        return self.num_rows

    def GetNumberCols(self):
        return self.num_cols

    def GetValue(self, row, col):
        if col == 0:
            return str(self.data[row][0])
        elif col == 1:
            return self.data[row][1]
        elif col == 2:
            return str(self.data[row][2])
        elif col == 3:
            return str(self.data[row][3])
        elif col == 4:
            return str(self.data[row][4])
        return ""

    def GetColLabelValue(self, col):
        return self.colLabels[col]

    def GetRowLabelValue(self, row):
        return self.rowLabels[row]  # Row labels (starting from 1)



#data flitter remove'host_about'column
def data_process():
    listings=pd.read_csv("dataset/listings_dec18.csv",low_memory=False)
    df=listings.drop(['host_about'],axis=1)
    df.to_csv("listings_dec18.csv",index=False,encoding="utf-8")

def creat_all_database():
    con = sqlite3.connect('Sydney_Airbnb.db')# connect with dataset
    data = pd.read_csv('dataset/calendar_dec18.csv')
    data.to_sql('Calendar_Dec18', con=con, if_exists='replace', index=False)
    data = pd.read_csv('dataset/listings_dec18.csv',low_memory=False)
    data.to_sql('Listings_Dec18', con=con, if_exists='replace', index=False)
    data = pd.read_csv('dataset/reviews_dec18.csv',low_memory=False)
    data.to_sql('Reviews_Dec18', con=con, if_exists='replace', index=False)




#property type
property=['Apartment',
        'House',
        'Townhouse',
        'Condominium',
        'Guest suite',
        'Guesthouse',
        'Villa',
        'Loft',
        'Serviced apartment',
        'Bed and breakfast',
        'Bungalow',
        'Cottage',
        'Boutique hotel',
        'Other',
        'Hostel',
        'Cabin',
        'Hotel',
        'Boat',
        'Tiny house',
        'Tent',
        'Camper/RV',
        'Farm stay',
        'Chalet',
        'Aparthotel',
        'Resort',
        'Yurt',
        'Hut',
        'Casa particular(Cuba)',
        'Island',
        'Campsite',
        'Earth house',
        'Heritage hotel(India)',
        'Tipi',
        'Treehouse',
        'Nature lodge',
        'Train',
        'Castle',
        'Barn',
        'Cave',
        'Dome house']

#drop down
distros = ['Bondi Beach, NSW, Australia',
        'Surry Hills, NSW, Australia',
        'Manly, NSW, Australia',
        'Sydney, NSW, Australia',
        'Bondi, NSW, Australia',
        'Coogee, NSW, Australia',
        'Randwick, NSW, Australia',
        'Darlinghurst, NSW, Australia',
        'North Bondi, NSW, Australia',
        'Redfern, NSW, Australia',
        'Maroubra, NSW, Australia',
        'Newtown, NSW, Australia',
        'Bondi Junction, NSW, Australia',
        'Mosman, NSW, Australia',
        'Paddington, NSW, Australia',
        'Potts Point, NSW, Australia',
        'Waterloo, NSW, Australia',
        'Pyrmont, NSW, Australia',
        'Bronte, NSW, Australia',
        'Chippendale, NSW, Australia',
        'Dee Why, NSW, Australia',
        'Ultimo, NSW, Australia',
        'Zetland, NSW, Australia',
        'Mascot, NSW, Australia',
        'Glebe, NSW, Australia',
        'Rose Bay, NSW, Australia',
        'Freshwater, NSW, Australia',
        'Bellevue Hill, NSW, Australia',
        'Avalon Beach, NSW, Australia',
        'Marrickville, NSW, Australia',
        'Camperdown, NSW, Australia',
        'Kingsford, NSW, Australia',
        'Alexandria, NSW, Australia',
        'Erskineville, NSW, Australia',
        'North Sydney, NSW, Australia',
        'Kensington, NSW, Australia',
        'Woollahra, NSW, Australia',
        'Rosebery, NSW, Australia',
        'Elizabeth Bay, NSW, Australia',
        'Fairlight, NSW, Australia',
        'Haymarket, NSW, Australia',
        'Clovelly, NSW, Australia',
        'Sydney Olympic Park, NSW, Australia',
        'Balmain, NSW, Australia',
        'Neutral Bay, NSW, Australia',
        'Tamarama, NSW, Australia',
        'Leichhardt, NSW, Australia',
        'Wolli Creek, NSW, Australia',
        'Vaucluse, NSW, Australia',
        'Rozelle, NSW, Australia',
        'Chatswood, NSW, Australia',
        'Annandale, NSW, Australia',
        'Rushcutters Bay, NSW, Australia',
        'Newport, NSW, Australia',
        'Parramatta, NSW, Australia',
        'Queenscliff, NSW, Australia',
        'Cronulla, NSW, Australia',
        'Balgowlah, NSW, Australia',
        'Burwood, NSW, Australia',
        'Ashfield, NSW, Australia',
        'Cremorne, NSW, Australia',
        'Palm Beach, NSW, Australia',
        'Kirribilli, NSW, Australia',
        'Waverley, NSW, Australia',
        'Double Bay, NSW, Australia',
        'Woolloomooloo, NSW, Australia',
        'Rhodes, NSW, Australia',
        'Ryde, NSW, Australia',
        'Hurstville, NSW, Australia',
        'Forest Lodge, NSW, Australia',
        'Stanmore, NSW, Australia',
        'Millers Point, NSW, Australia',
        'Wentworth Point, NSW, Australia',
        'Epping, NSW, Australia',
        'Strathfield, NSW, Australia',
        'Mona Vale, NSW, Australia',
        'Narrabeen, NSW, Australia',
        'Arncliffe, NSW, Australia',
        'Collaroy, NSW, Australia',
        'North Ryde, NSW, Australia',
        'Edgecliff, NSW, Australia',
        'Centennial Park, NSW, Australia',
        'Darlington, NSW, Australia',
        'Dulwich Hill, NSW, Australia',
        'Crows Nest, NSW, Australia',
        'Rockdale, NSW, Australia',
        'Wollstonecraft, NSW, Australia',
        'Manly Vale, NSW, Australia',
        'Drummoyne, NSW, Australia',
        'Petersham, NSW, Australia',
        'North Narrabeen, NSW, Australia',
        'Eastwood, NSW, Australia',
        'North Curl Curl, NSW, Australia',
        'Cammeray, NSW, Australia',
        'Enmore, NSW, Australia',
        'Lilyfield, NSW, Australia',
        'Lane Cove, NSW, Australia',
        'South Coogee, NSW, Australia',
        'McMahons Point, NSW, Australia',
        'Queens Park, NSW, Australia',
        'Marsfield, NSW, Australia',
        'Darling Point, NSW, Australia',
        'Campsie, NSW, Australia',
        'Dover Heights, NSW, Australia',
        'Birchgrove, NSW, Australia',
        'Seaforth, NSW, Australia',
        'Greenwich, NSW, Australia',
        'Curl Curl, NSW, Australia',
        'Lane Cove North, NSW, Australia',
        'Summer Hill, NSW, Australia',
        'North Balgowlah, NSW, Australia',
        'Homebush, NSW, Australia',
        'Little Bay, NSW, Australia',
        'Kogarah, NSW, Australia',
        'Brighton-Le-Sands, NSW, Australia',
        'Allambie Heights, NSW, Australia',
        'Bankstown, NSW, Australia',
        'Botany, NSW, Australia',
        'Macquarie Park, NSW, Australia',
        'Warriewood, NSW, Australia',
        'Roseville, NSW, Australia',
        'Hornsby, NSW, Australia',
        'Canterbury, NSW, Australia',
        'Bundeena, NSW, Australia',
        'Milsons Point, NSW, Australia',
        'North Manly, NSW, Australia',
        'Balgowlah Heights, NSW, Australia',
        'Castle Hill, NSW, Australia',
        'Saint Peters, NSW, Australia',
        'Gladesville, NSW, Australia',
        'Lewisham, NSW, Australia',
        'Frenchs Forest, NSW, Australia',
        'St Leonards, NSW, Australia',
        'Earlwood, NSW, Australia',
        'Cremorne Point, NSW, Australia',
        'Carlingford, NSW, Australia',
        'Balmain East, NSW, Australia',
        'Homebush West, NSW, Australia',
        'Croydon, NSW, Australia',
        'Willoughby, NSW, Australia',
        'Naremburn, NSW, Australia',
        'Hillsdale, NSW, Australia',
        'Matraville, NSW, Australia',
        'Hunters Hill, NSW, Australia',
        'Beacon Hill, NSW, Australia',
        'Auburn, NSW, Australia',
        'Artarmon, NSW, Australia',
        'Waverton, NSW, Australia',
        'Bilgola Plateau, NSW, Australia',
        'Lindfield, NSW, Australia',
        'Riverwood, NSW, Australia',
        'Bexley, NSW, Australia',
        'Sans Souci, NSW, Australia',
        'Pymble, NSW, Australia',
        'Whale Beach, NSW, Australia',
        'Turrella, NSW, Australia',
        'Blacktown, NSW, Australia',
        'Eastlakes, NSW, Australia',
        'Merrylands, NSW, Australia',
        'Granville, NSW, Australia',
        'Baulkham Hills, NSW, Australia',
        'Beaconsfield, NSW, Australia',
        'Saint Leonards, NSW, Australia',
        'Sydney , NSW, Australia',
        'Wahroonga, NSW, Australia',
        'Avalon, NSW, Australia',
        'West Ryde, NSW, Australia',
        'Chiswick, NSW, Australia',
        'Killara, NSW, Australia',
        'Lidcombe, NSW, Australia',
        'Bilgola Beach, NSW, Australia',
        'Gordon, NSW, Australia',
        'Malabar, NSW, Australia',
        'Pagewood, NSW, Australia',
        'Collaroy Plateau, NSW, Australia',
        'Turramurra, NSW, Australia',
        'Glenwood, NSW, Australia',
        'Monterey, NSW, Australia',
        'North Parramatta, NSW, Australia',
        'Liverpool, NSW, Australia',
        'The Rocks, NSW, Australia',
        'Clontarf, NSW, Australia',
        'Tempe, NSW, Australia',
        'Forestville, NSW, Australia',
        'Ermington, NSW, Australia',
        'Brookvale, NSW, Australia',
        'NSW, NSW, Australia',
        'Cromer, NSW, Australia',
        'Westmead, NSW, Australia',
        'Padstow, NSW, Australia',
        'Beverly Hills, NSW, Australia',
        'Lane Cove West, NSW, Australia',
        'Lavender Bay, NSW, Australia',
        'Saint Ives, NSW, Australia',
        'Glenfield, NSW, Australia',
        'Campbelltown, NSW, Australia',
        'Belrose, NSW, Australia',
        'Croydon Park, NSW, Australia',
        'Kingsgrove, NSW, Australia',
        'West Pennant Hills, NSW, Australia',
        'Kurraba Point, NSW, Australia',
        'Hurlstone Park, NSW, Australia',
        'Eastgardens, NSW, Australia',
        'Penrith, NSW, Australia',
        'Watsons Bay, NSW, Australia',
        'Clareville, NSW, Australia',
        'Penshurst, NSW, Australia',
        'Revesby, NSW, Australia',
        'Quakers Hill, NSW, Australia',
        'Narraweena, NSW, Australia',
        'Guildford, NSW, Australia',
        'Belmore, NSW, Australia',
        'Miranda, NSW, Australia',
        'Meadowbank, NSW, Australia',
        'Bayview, NSW, Australia',
        'Scotland Island, NSW, Australia',
        'Haberfield, NSW, Australia',
        'Lakemba, NSW, Australia',
        'Five Dock, NSW, Australia',
        'Cherrybrook, NSW, Australia',
        'North Willoughby, NSW, Australia',
        'Waitara, NSW, Australia',
        'Beecroft, NSW, Australia',
        'Banksia, NSW, Australia',
        'Northbridge, NSW, Australia',
        'Carlton, NSW, Australia',
        'Rosehill, NSW, Australia',
        'Abbotsford, NSW, Australia',
        'Sydenham, NSW, Australia',
        'Longueville, NSW, Australia',
        'Kellyville, NSW, Australia',
        'Northmead, NSW, Australia',
        'Dundas Valley, NSW, Australia',
        'Caringbah, NSW, Australia',
        'Council of the City of Sydney, NSW, Australia',
        'Sylvania, NSW, Australia',
        'Great Mackerel Beach, NSW, Australia',
        'Russell Lea, NSW, Australia',
        'Newington, NSW, Australia',
        'Dangar Island, NSW, Australia',
        'North Rocks, NSW, Australia',
        'Oatley, NSW, Australia',
        'Church Point, NSW, Australia',
        'Breakfast Point, NSW, Australia',
        'Harris Park, NSW, Australia',
        'Rouse Hill, NSW, Australia',
        'Pennant Hills, NSW, Australia',
        'Dundas, NSW, Australia',
        'Gymea, NSW, Australia',
        'Elanora Heights, NSW, Australia',
        'Jannali, NSW, Australia',
        'Chatswood West, NSW, Australia',
        'Killarney Heights, NSW, Australia',
        'South Wentworthville, NSW, Australia',
        'Sandringham, NSW, Australia',
        'Concord, NSW, Australia',
        'Caringbah South, NSW, Australia',
        'Mortdale, NSW, Australia',
        'Punchbowl, NSW, Australia',
        'Castlecrag, NSW, Australia',
        'Castle Cove, NSW, Australia',
        'Berowra Waters, NSW, Australia',
        'Point Piper, NSW, Australia',
        'Kingswood, NSW, Australia',
        'Winston Hills, NSW, Australia',
        'Thornleigh, NSW, Australia',
        'Wareemba, NSW, Australia',
        'Kellyville Ridge, NSW, Australia',
        'Casula, NSW, Australia',
        'Berala, NSW, Australia',
        'Putney, NSW, Australia',
        'Rooty Hill, NSW, Australia',
        'Enfield, NSW, Australia',
        'Toongabbie, NSW, Australia',
        'Wentworthville, NSW, Australia',
        'Davidson, NSW, Australia',
        'Yagoona, NSW, Australia',
        'Woolooware, NSW, Australia',
        'Liberty Grove, NSW, Australia',
        'Bella Vista, NSW, Australia',
        'Kurnell, NSW, Australia',
        'Kings Langley, NSW, Australia',
        'Northwood, NSW, Australia',
        'Cabramatta, NSW, Australia',
        'Carnes Hill, NSW, Australia',
        'Willoughby East, NSW, Australia',
        'Peakhurst, NSW, Australia',
        'Chester Hill, NSW, Australia',
        'Wisemans Ferry, NSW, Australia',
        'Greenacre, NSW, Australia',
        'Seven Hills, NSW, Australia',
        'Rydalmere, NSW, Australia',
        'The Ponds, NSW, Australia',
        'Darlinghurst, Australia',
        'Como, NSW, Australia',
        'Dural, NSW, Australia',
        'East Lindfield, NSW, Australia',
        'Beaumont Hills, NSW, Australia',
        'Sydney Olympic Park, Australia',
        'Blakehurst, NSW, Australia',
        'Maianbar, NSW, Australia',
        'Sutherland, NSW, Australia',
        'Saint Clair, NSW, Australia',
        'South Hurstville, NSW, Australia',
        'Milsons Passage, NSW, Australia',
        'Cranebrook, NSW, Australia',
        'Moorebank, NSW, Australia',
        'Riverview, NSW, Australia',
        'Middle Dural, NSW, Australia',
        'Chifley, NSW, Australia',
        'Manly, Australia',
        'Dawes Point, NSW, Australia',
        'Telopea, NSW, Australia',
        'Denistone East, NSW, Australia',
        'Werrington, NSW, Australia',
        'Warwick Farm, NSW, Australia',
        'Connells Point, NSW, Australia',
        'Belfield, NSW, Australia',
        'Asquith, NSW, Australia',
        'Ingleburn, NSW, Australia',
        'Emu Plains, NSW, Australia',
        'Jamisontown, NSW, Australia',
        'North Epping, NSW, Australia',
        'Kenthurst, NSW, Australia',
        'Bardwell Valley, NSW, Australia',
        'Wiley Park, NSW, Australia',
        'darling harbour, NSW, Australia',
        'Fairfield, NSW, Australia',
        'Pyrmont, Australia',
        'West Pymble, NSW, Australia',
        'Warrawee, NSW, Australia',
        'St Peters, NSW, Australia',
        'Wheeler Heights, NSW, Australia',
        'Eveleigh, NSW, Australia',
        'North Strathfield, NSW, Australia',
        'Burraneer, NSW, Australia',
        'Allawah, NSW, Australia',
        'Daceyville, NSW, Australia',
        'Bondi , NSW, Australia',
        'Panania, NSW, Australia',
        'Manly Beach, NSW, Australia',
        'Brooklyn, NSW, Australia',
        'Yennora, NSW, Australia',
        'Oxley Park, NSW, Australia',
        'Glenmore Park, NSW, Australia',
        'Saint Marys, NSW, Australia',
        'Silverwater, NSW, Australia',
        'Prestons, NSW, Australia',
        'Waverley Council, NSW, Australia',
        'Bexley North, NSW, Australia',
        'Heathcote, NSW, Australia',
        'Kyeemagh, NSW, Australia',
        'Hurstville Grove, NSW, Australia',
        'Merrylands West, NSW, Australia',
        'Kirrawee, NSW, Australia',
        'Cottage Point, NSW, Australia',
        '• Darling harbour, NSW, Australia',
        'Pemulwuy, NSW, Australia',
        'Mortlake, NSW, Australia',
        'Oatlands, NSW, Australia',
        'Narwee, NSW, Australia',
        'Carramar, NSW, Australia',
        'Roselands, NSW, Australia',
        'Greystanes, NSW, Australia',
        'Saint Ives Chase, NSW, Australia',
        'Smithfield, NSW, Australia',
        'Schofields, NSW, Australia',
        'Henley, NSW, Australia',
        'Normanhurst, NSW, Australia',
        'Huntleys Cove, NSW, Australia',
        'Woolwich, NSW, Australia',
        'Kings Cross, Sydney, Australia',
        'Dolls Point, NSW, Australia',
        'Mount Druitt, NSW, Australia',
        'Berowra, NSW, Australia',
        'Bondi Beach, Australia',
        'Kogarah Bay, NSW, Australia',
        'East Hills, NSW, Australia',
        'St Ives, NSW, Australia',
        'Sylvania Waters, NSW, Australia',
        'Doonside, NSW, Australia',
        'Mosman, Australia',
        'Plumpton, NSW, Australia',
        'Cheltenham, NSW, Australia',
        'Oyster Bay, NSW, Australia',
        'Macquarie Fields, NSW, Australia',
        'Grays Point, NSW, Australia',
        'The Rocks/Circular Quay Sydney, NSW, Australia',
        'Berowra Heights, NSW, Australia',
        'BONDI, NSW, Australia',
        'Coasters Retreat, NSW, Australia',
        'Guildford West, NSW, Australia',
        'Linley Point, NSW, Australia',
        'La Perouse, NSW, Australia',
        'Potts Point, Australia',
        'Denistone, NSW, Australia',
        'Holsworthy, NSW, Australia',
        'Mount Annan, NSW, Australia',
        'Lovett Bay, NSW, Australia',
        'Barangaroo, NSW, Australia',
        'Woodcroft, NSW, Australia',
        'Minto, NSW, Australia',
        'Prospect, NSW, Australia',
        'Regents Park, NSW, Australia',
        'Galston, NSW, Australia',
        'Marsden Park, NSW, Australia',
        'Bardia, NSW, Australia',
        'Illawong, NSW, Australia',
        'Elderslie, NSW, Australia',
        'West Hoxton, NSW, Australia',
        'Constitution Hill, NSW, Australia',
        'Bondi Junction , NSW, Australia',
        'sydney, NSW, Australia',
        'Ingleside, NSW, Australia',
        'Concord West, NSW, Australia',
        'Stanhope Gardens, NSW, Australia',
        'North Turramurra, NSW, Australia',
        'Strathfield South, NSW, Australia',
        'Annangrove, NSW, Australia',
        'Roseville Chase, NSW, Australia',
        'Berowra Creek, NSW, Australia',
        'Lugarno, NSW, Australia',
        'Bass Hill, NSW, Australia',
        'Glenorie, NSW, Australia',
        'Padstow Heights, NSW, Australia',
        'Holroyd, NSW, Australia',
        'Bondi beach , NSW, Australia',
        'Engadine, NSW, Australia',
        'Ramsgate, NSW, Australia',
        'Pendle Hill, NSW, Australia',
        'Sydney , Nsw, Australia',
        'Phillip Bay, NSW, Australia',
        '悉尼, NSW, Australia',
        'Glen Alpine, NSW, Australia',
        'Hornsby Heights, NSW, Australia',
        'Marayong, NSW, Australia',
        'East Ryde, NSW, Australia',
        'Terrey Hills, NSW, Australia',
        'Bardwell Park, NSW, Australia',
        'South Turramurra, NSW, Australia',
        'Coogee, Australia',
        'Fairfield Heights, NSW, Australia',
        'Jordan Springs, NSW, Australia',
        'Oran Park, NSW, Australia',
        'Edmondson Park, NSW, Australia',
        'Old Toongabbie, NSW, Australia',
        'South Penrith, NSW, Australia',
        'Morning Bay, NSW, Australia',
        'Bonnyrigg, NSW, Australia',
        'Bungarribee, NSW, Australia',
        'Lilli Pilli, NSW, Australia',
        'Kings Park, NSW, Australia',
        'Chippendale , NSW, Australia',
        'Cremorne, Australia',
        'Zetland, Australia',
        'Waterloo, Australia',
        'Pyrmont , NSW, Australia',
        'Fairfield West, NSW, Australia',
        'Greenhills Beach, NSW, Australia',
        'Bronte, Australia',
        'Millers Point, Australia',
        'Bondi Junction, Australia',
        'Bonnyrigg Heights, NSW, Australia',
        'Randwick City Council, NSW, Australia',
        'Acacia Gardens, NSW, Australia',
        'Lansvale, NSW, Australia',
        'Canoelands, NSW, Australia',
        'Duffys Forest, NSW, Australia',
        'Mount Colah, NSW, Australia',
        'Rushcutters Bay , NSW, Australia',
        'Mascot, Australia',
        'Yarrawarrah, NSW, Australia',
        'Saint Helens Park, NSW, Australia',
        'Bondi Beach , NSW, Australia',
        'Luddenham, NSW, Australia',
        'Woolloomooloo , NSW, Australia',
        'Cabramatta West, NSW, Australia',
        'Blair Athol, NSW, Australia',
        'Birchgrove, Australia',
        'Carss Park, NSW, Australia',
        'Harrington Park, NSW, Australia',
        'Newport Beach, NSW, Australia',
        'Ashbury, NSW, Australia',
        'Marrickville , NSW, Australia',
        'Rhodes, Australia',
        'Sandy Point, NSW, Australia',
        'Surry hills, NSW, Australia',
        'Canada Bay, NSW, Australia',
        'Clovelly , NSW, Australia',
        'Bondi Junction, Sydney, NSW, Australia',
        'Loftus, NSW, Australia',
        'Rodd Point, NSW, Australia',
        'Ramsgate Beach, NSW, Australia',
        'Bossley Park, NSW, Australia',
        'Wattle Grove, NSW, Australia',
        'Bondi beach, NSW, Australia',
        'Bondi Beach, Sydney, NSW, Australia',
        'Leumeah, NSW, Australia',
        'Eastern Creek, NSW, Australia',
        'Elvina Bay, NSW, Australia',
        'Canley Vale, NSW, Australia',
        'Auburn , NSW, Australia',
        'Surry Hills NSW 2010, Surry Hills NSW 2010, Australia',
        'Rossmore, NSW, Australia',
        'Redfern, Australia',
        'Paddington, Australia',
        'Pittwater Council, NSW, Australia',
        'East Redfern, NSW, Australia',
        'Ropes Crossing, NSW, Australia',
        'Woodbine, NSW, Australia',
        'Glenhaven, NSW, Australia',
        'Woronora, NSW, Australia',
        'Newtown , NSW, Australia',
        'Tennyson Point, NSW, Australia',
        'Wolli Creek , NSW, Australia',
        'Coogee , NSW, Australia',
        'Cattai, NSW, Australia',
        'Maroubra, Australia',
        'Dean Park, NSW, Australia',
        'Manly , NSW, Australia',
        'Bangor, NSW, Australia',
        'Rockdale City Council, NSW, Australia',
        'North Wahroonga, NSW, Australia',
        'South Wentworthville, Australia, Australia',
        'North Bondi , NSW, Australia',
        'Eastgardens , NSW, Australia',
        'Tamarama, Australia',
        'Sydney, Australia',
        'North Sydney NSW 2060, North Sydney NSW 2060, Australia',
        'CAMPERDOWN, NSW, Australia',
        'Cabarita, NSW, Australia',
        'Oxford Falls, NSW, Australia',
        'Sydney CBD, NSW, Australia',
        'Haymarket NSW 2000, Haymarket NSW 2000, Australia',
        'Westleigh, NSW, Australia',
        'Hammondville, NSW, Australia',
        'Bilgola, NSW, Australia',
        'Camden, NSW, Australia',
        'Chipping Norton, NSW, Australia',
        'Waterfall, NSW, Australia',
        'Bellevue Hill, Sydney, NSW, Australia',
        'Collaroy Beach, NSW, Australia',
        'Saint Johns Park, NSW, Australia',
        'Rosebery, Australia',
        'Kareela, NSW, Australia',
        'Wentworth Point , NSW, Australia',
        'Bellevue Hill, Sydney, Australia',
        'Sefton, NSW, Australia',
        'Parklea, NSW, Australia',
        'Lalor Park, NSW, Australia',
        'Annandale, Australia',
        'Wolli Creek, Australia',
        'City of Canada Bay Council, NSW, Australia',
        'Surry Hills , NSW, Australia',
        'Double Bay, Sydney, NSW, Australia',
        'Elizabeth Bay, Australia',
        'Botany Bay, NSW, Australia',
        'Mays Hill, NSW, Australia',
        'Middleton Grange, NSW, Australia',
        'Rose Bay, Sydney, NSW, Australia',
        'Clemton Park , NSW, Australia',
        'Catherine Field, NSW, Australia',
        'Middle Cove, NSW, Australia',
        'Werrington Downs, NSW, Australia',
        'Lower Portland, NSW, Australia',
        'Raby, NSW, Australia',
        'Canley Heights, NSW, Australia',
        'Alexandria, Australia',
        'Potts Point , NSW, Australia',
        'Randwick , NSW, Australia',
        'Forest Lodge, Australia',
        'Lurnea, NSW, Australia',
        'Macquarie Links, NSW, Australia',
        'Bondi junction, Nsw, Australia',
        'Chatswood NSW 2067, Chatswood NSW 2067, Australia',
        'Colyton, NSW, Australia',
        'Wollstonecraft , NSW, Australia',
        'Yowie Bay, NSW, Australia',
        'Old Guildford, NSW, Australia',
        'Oakhurst, NSW, Australia',
        'Balmoral Beach, NSW, Australia',
        'Condell Park, NSW, Australia',
        'Villawood, NSW, Australia',
        'Leonay, NSW, Australia',
        'Abbotsbury, NSW, Australia',
        'Emu Heights, NSW, Australia',
        'North St Marys, NSW, Australia',
        'Beverley Park, NSW, Australia',
        'Arcadia, NSW, Australia',
        'Sydney, Australia, Australia',
        'Hurstville , NSW, Australia',
        'Cartwright, NSW, Australia',
        'Taren Point, NSW, Australia',
        'Glebe, Sydney, NSW, Australia',
        'Mulgoa, NSW, Australia',
        'Fairlight , NSW, Australia',
        'McMahons Point, Sydney, NSW, Australia',
        'Horningsea Park, NSW, Australia',
        'Bonnet Bay, NSW, Australia',
        'Potts Hill, NSW, Australia',
        'Bronte , NSW, Australia',
        'Elizabeth Bay, SYDNEY , Australia',
        'SYDNEY , Nsw, Australia',
        'North Sydney, NW, Australia',
        'NSW, Sydney, Australia',
        'Burwood , Nsw, Australia',
        'Wentworth Point, Australia',
        'Freshwater, Australia',
        'Westmead , NSW, Australia',
        'Camperdown, NW, Australia',
        'North Bondi Beach, NSW, Australia',
        'Wentworth Point, NSW 2127, Australia',
        'Sydney, Nsw, Australia',
        'Chiswick, Australia',
        'Turella, NSW, Australia',
        'waterloo, NSW, Australia',
        'Barpoint , NSW, Australia',
        'St Clair, NSW, Australia',
        'Leichhardt, Australia',
        'McMahons Point, Australia',
        'Balgowlah, Australia',
        'Sydney , Auburn, Australia',
        'Milsons Point, Australia',
        ' Surry Hills, nsw, Australia',
        'Sydney, Bondi Beach , NSW, Australia',
        'Bondi Beach, NSW 2026, Australia',
        'Greenfield Park, NSW, Australia',
        'Sydney Olympic Park, NSW 2127, Australia',
        'Alexandria , NSW, Australia',
        'Bronte, Sydney , NSW, Australia',
        'Harris Park, Australia',
        'Clyde, NSW, Australia',
        'Leichhardt Municipal Council, NSW, Australia',
        'St. Leonards , NSW, Australia',
        'summer hill, Nsw, Australia',
        'Wentworth point, NSW, Australia',
        ' Bondi Beach, NSW, Australia',
        'wenworth point , NSW, Australia',
        'Sydney Olympic Park , NSW, Australia',
        'Darlinghurst , NSW, Australia',
        'Balgowlah , NSW, Australia',
        'Sydney, NSW 2000, Australia',
        'Chatswood Sydney , NSW, Australia',
        'North Sydney , NSW, Australia',
        'Castlereagh, NSW, Australia',
        'Turella, NSW 2205, Australia',
        'Wentworth Point Sydney, NSW, Australia',
        'Erskine Park, NSW, Australia',
        'Dolans Bay, NSW, Australia',
        'Allambie Heights , NSW, Australia',
        'Caddens, NSW, Australia',
        'Maraylya, NSW, Australia',
        'Pyrmont, NW, Australia',
        'Toongabbie East, NSW, Australia',
        'Surry Hills, Australia',
        'Edgecliff, Australia',
        'Rozelle / Balmain, NSW, Australia',
        'KENSINGTON, NSW, Australia',
        'North Ryde , NSW, Australia',
        'Minchinbury, NSW, Australia',
        'Sackville, NSW, Australia',
        'Greendale, NSW, Australia',
        'North Sydney Council, NSW, Australia',
        'Parramatta , NSW, Australia',
        'Guildford , NSW, Australia',
        'Botany , NSW, Australia',
        '悉尼, 新州, Australia',
        'South Coogee, Australia',
        'Balmain East, Australia',
        'Beverly Hills , NSW, Australia',
        'Parramatta, Australia',
        'Ringwood, VIC, Australia',
        'Mount Druitt NSW 2770, Mount Druitt NSW 2770, Australia',
        'Auburn / Lidcomb , NSW, Australia',
        'Clovelly, Australia',
        'Currans Hill, NSW, Australia',
        'Allawah , NSW, Australia',
        'Seaforth , NSW, Australia',
        'Rozelle, Australia',
        'Maroubra beach, NSW, Australia',
        'Kensignton, NSW, Australia',
        'Glebe, Nsw, Australia',
        'Redfern NSW 2016, Redfern NSW 2016, Australia',
        'Pagewood SYDNEY, NSW, Australia',
        'Kellyville NSW 2155, Kellyville NSW 2155, Australia',
        'Balmain , NSW, Australia',
        'Coogee beach, NSW, Australia',
        'Marrickville, Australia',
        'Parramatta NSW 2151, Parramatta NSW 2151, Australia',
        'Spencer, NSW, Australia',
        'Waverton , Nsw, Australia',
        'Sydney, Randwick, Australia',
        'Mullumbimby, NSW, Australia',
        'Neutral Bay, Australia',
        'Zetland, Australia, Australia',
        'Macquarie Park, Australia',
        'Newtown, Australia',
        'Fairlight , Nsw, Australia',
        'Lane Cove Municipal Council, NSW, Australia',
        'Glen Waverley, VIC, Australia',
        'Sackville North, NSW, Australia',
        'Voyager Point, NSW, Australia',
        'Lewisham , NSW, Australia',
        'NSW, Manly, Australia',
        'Waterloo , NSW, Australia',
        'Camperdown, Australia',
        'Haberfield , NSW, Australia',
        'Prairiewood, NSW, Australia',
        'Coogee Beach, NSW, Australia',
        'Agnes Banks, NSW, Australia',
        'Dawes Point, Australia',
        'Colebee, NSW, Australia',
        'Waterloo , Nsw, Australia',
        'Frenchs Forest, Australia',
        'Berowra waters , NSW, Australia',
        'Waverley, Australia',
        'Menai, NSW, Australia',
        'NSW sydney, NSW, Australia',
        'Belrose, Australia',
        'East Killara, NSW, Australia',
        'Bradbury, NSW, Australia',
        'Ultimo, Australia',
        'South Granville, NSW, Australia',
        'Woolloomooloo, Australia',
        'Kirawee , NSW, Australia',
        'Sydney, Sydney, Australia',
        'Dee Why Beach, NSW, Australia',
        'Balmain, Australia',
        'Kirribilli, Australia',
        'Edgecliff, Nsw, Australia',
        'Leppington, NSW, Australia',
        'North Bondi, Australia',
        'Ultimo , NSW, Australia',
        'Bundoora, VIC, Australia',
        'Haymarket, Australia',
        'Ashfield , NSW, Australia',
        'The Rocks, Sydney, NSW, Australia',
        'Waterloo, NW, Australia',
        'sdyney, NSW, Australia',
        'Redfern , NSW, Australia',
        'Brookvale, Australia',
        'Banksia Sydney, NSW, Australia',
        'Whalan, NSW, Australia',
        'Banksmeadow, NSW, Australia',
        'North Sydney / Waverton, NSW, Australia',
        'Hornsby nsw Australia , NSW, Australia',
        'Surry Hills, New South Wales, AU, NSW, Australia',
        'St Leonards , NSW, Australia',
        'Leets Vale, NSW, Australia',
        'Maroubra, New South Wales, AU, NSW, Australia',
        'Southport, QLD, Australia',
        'Seven Hills    , NSW, Australia',
        'lewisham, nsw, Australia',
        'Monterey, New South Wales, AU, NSW, Australia',
        'Kareela, Sydney, NSW, Australia',
        'Wollstonecraft, Sydney, NSW, Australia',
        'Greenacre, New South Wales, AU, NSW, Australia',
        'norfolk rd. \nNorth Epping, NSW, Australia',
        'Sydney, Bondi Beach, NSW, Australia',
        'Little bay, Nsw, Australia',
        'Cobbitty, NSW, Australia',
        'Orchard Hills, NSW, Australia',
        'Wolli Creek, nsw, Australia',
        'Rozelle Sydney, NSW, Australia',
        'Hinchinbrook, NSW, Australia',
        'Waverton, North Sydney, NSW, Australia',
        'St Peters /Newtown, NSW, Australia',
        'Neutral Bay , NSW, Australia',
        'Manly/Queenscliff, NSW, Australia',
        'North Sydney / Kirribilli, NSW, Australia',
        'Ashfield, New South Wales, AU, Sydney, Australia',
        'Darlinghurst, Sydney, NSW, Australia',
        'Bondi Junction, New South Wales, AU, nsw, Australia',
        'Clontarf, Sydney, NSW, Australia',
        'Paddington / Sydney, NSW, Australia',
        'Darlinghurst Sydney, NSW, Australia',
        'Moore Park, NSW, Australia',
        'Revesby Heights, NSW, Australia',
        'Rose bay , NSW, Australia',
        'sydney , nsw, Australia',
        'Elizabeth Bay , NSW, Australia',
        'Mosman Sydney, NSW, Australia',
        'Bondi Junction, Sydney, Australia',
        'Glenfield, Nsw, Australia',
        'Centennial Park, Sydney, NSW, Australia',
        'Centennial Park, Nsw, Australia',
        'Clovelly, Sydney, NSW, Australia',
        'Mccarrs Creek, NSW, Australia',
        'Marrickville, Nsw, Australia',
        'Manly, Nsw, Australia',
        'Balmain / Birchgrove, NSW, Australia',
        "Watson's Bay, NSW, Australia",
        'Forest lodge, NSW, Australia',
        'Rosebery, Nsw, Australia',
        'Kirkham, NSW, Australia',
        'Hillsdale, Sydney, NSW, Australia',
        'Ashbury, Sydney, NSW, Australia',
        'Port Jackson, Australia',
        'Lilyfield , NSW, Australia',
        'Rose bay, NSW, Australia',
        'Minto Heights, NSW, Australia',
        'North Curl Curl (near Manly), NSW, Australia',
        'Oran park, NSW, Australia',
        'Sydney, New, Australia',
        'Sydney City, NSW, Australia',
        'Fiddletown, NSW, Australia',
        'Kensington, Sydney, NSW, Australia',
        'Narrabeen , NSW, Australia',
        'Rockdale\nRockdale, NSW, Australia',
        'Millers Point, Sydney, NSW, Australia',
        'Roseville , NSW, Australia',
        'Bilgola / Avalon, NSW, Australia',
        'Camden South, NSW, Australia',
        'zetland, NSW, Australia',
        'Pitt Town, NSW, Australia',
        '9/20 botany street , NSW, Australia',
        'rooty hill, NSW, Australia',
        'South Maroota, NSW, Australia',
        'Bilgola, Sydney, NSW, Australia',
        'Maroubra Beach, NSW, Australia',
        'Warriewood Beach, NSW, Australia',
        'Collaroy Beach , NSW, Australia',
        'Kyle Bay, NSW, Australia',
        'Rhodes , NSW, Australia',
        'Bar Point, NSW, Australia',
        'New South Wales, Sydney, Australia',
        'rose bay, nsw, Australia',
        'Allawah/Carlton, NSW, Australia',
        'Mount Vernon, NSW, Australia',
        'Marrickville/Sydney, NSW, Australia',
        'Darling Harbour, NSW, Australia',
        'St Ives Chase, NSW, Australia',
        'Kensington , NSW, Australia',
        'Homebush west, nsw, Australia',
        'Bondi Junction Sydney , NSW, Australia',
        ' Coogee ,Sydney, NSW, Australia',
        'Burwood Heights, NSW, Australia',
        'Northern Beaches, NSW, Australia',
        'Erskineville, Australia',
        'Bondi junction , NSW, Australia',
        'Queens park, NSW, Australia',
        'Peakhurst Heights, NSW, Australia',
        'Nelson, NSW, Australia',
        'Chatswood, Sydney , NSW, Australia',
        'Royal National Park, NSW, Australia',
        'Ambarvale, NSW, Australia',
        'Dee Why, Sydney, NSW, Australia',
        'Queens Park , NSW, Australia',
        'Crows Nest, Sydney, NSW, Australia',
        'Greystanes , NSW, Australia',
        'New South Wales , NSW, Australia',
        'Maroubra,, NSW, Australia',
        'Darlington , NSW, Australia',
        'Rozelle, Sydney, NSW, Australia',
        'Redfern, Nueva Gales del Sur, Australia',
        'Parramatta City Council, NSW, Australia',
        'Croydon Park NSW, NSW, Australia',
        'Bellevue hill , NSW, Australia',
        'Eagle Vale, NSW, Australia',
        'Mount Pritchard, NSW, Australia',
        'Willoughby City Council, NSW, Australia',
        'Pyrmont, Nsw, Australia',
        'Barangaroo , NSW, Australia',
        'Paddington , NSW, Australia',
        'Bellevue Hill (Double Bay side)., NSW, Australia',
        'Ashfield Sydney, NSW, Australia',
        'Hurstville Sydney, NSW, Australia',
        'Melrose Park, NSW, Australia',
        'Mount Kuring-Gai, NSW, Australia',
        'Gymea Bay, NSW, Australia',
        'Bondi, Tamarama, NSW, Australia',
        'Sydney, Mascot, NSW, Australia',
        'Elizabeth Bay /Potts Point, NSW, Australia',
        'Ku-Ring-Gai Council, NSW, Australia',
        'Ku-Ring-Gai Chase, NSW, Australia',
        'Gregory Hills, NSW, Australia',
        'Bondi, Sydney, NSW, Australia',
        'Elizabeth Bay / Sydney, NSW, Australia',
        'Kentlyn, NSW, Australia',
        'Berrilee, NSW, Australia',
        'Wentworth point, Nsw, Australia',
        'Cowan, NSW, Australia',
        'Potts Point, New South Wales, AU, NSW, Australia',
        'Penrith, New South Wales, AU, NSW, Australia',
        'camperdown, NSW, Australia',
        'Newport, New South Wales, AU, NSW, Australia',
        '悉尼市, NSW, Australia',
        'Sydney, New South Wales, Australia, nsw, Australia',
        'Tamarama , NSW, Australia',
        'Manly, New South Wales, AU, nsw, Australia',
        'Manly, New South Wales, AU, Manly, Australia',
        'Kogarah , NSW, Australia',
        'Wollarha, NSW, Australia',
        'Campbelltown, New South Wales, AU, Macarthur, Australia',
        'brookvale , nsw, Australia',
        'Balgowlah / Manly, NSW, Australia',
        'Bondi Beach, New South Wales, AU, NSW, Australia',
        'Petersham , Nsw, Australia',
        'Burraneer/Cronulla, NSW, Australia',
        'Fairlight (Manly), NSW, Australia',
        'Double Bay, New South Wales, AU, nsw, Australia',
        'Potts point , NSW, Australia',
        'Coogee, Nsw, Australia',
        'Surry Hills Sydney , NSW, Australia',
        'Dover heights, NSW, Australia',
        'Paddington/Woollahra, NSW, Australia',
        'Hassall Grove, NSW, Australia',
        'Girraween, NSW, Australia',
        'Balgowlah Heights, Australia',
        'bondi beach, Australia, Australia',
        'Denham Court, NSW, Australia',
        'Potts Points, NSW, Australia',
        'Enmore, Nsw, Australia',
        '石谷市, NSW, Australia',
        'Brighton Le Sands, NSW, Australia',
        '웬트워스 포인트, NSW, Australia',
        'Maroota, NSW, Australia',
        'Manly, New South Wales, AU, sydney, Australia',
        'Gladesville, New South Wales, AU, NSW, Australia',
        'pyrmont, NSW, Australia',
        'Coogee, New South Wales, Australia, NSW, Australia',
        'Seaforth, Australia']



if __name__ == '__main__':
    #create dataset
    creat_all_database()
